# используем язык java. Travis CI поддерживает другие языки тоже.
language: java

jdk: openjdk13

os: windows


services: postgresql

before_install: psql -c 'create database tracker;' -U postgres

after_success: bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      kirbel74@gmail.com
    on_success: never # default: change
    on_failure: always # default: always


env:
  global: CODECOV_TOKEN="a362e2c6-fb7f-496d-baba-1f6c5c542e12"